### ISSUE TITLE
A little help 

### ISSUE THREAD

**Issue by ChevalierLouis** [pigrew/pyvxi11aio#1]
Hello, I want to know if it's possible to run the server on e other  IP address? And also in which file can I go to make some actions like using the gpios 

I have try this one https://github.com/coburnw/python-vxi11-server  and it run nice on the Pi 3 b v1.2 but it didn't run on the pi4 and the comput module 4 

have a good day 

louis Chevalier

**Comment by pigrew** [comment]
The RPC server is configured to only listen to localhost, see https://github.com/pigrew/pyvxi11aio/blob/b1a02af8cc0c2e852bbe5c238d0ef612b4bd4c95/vxi11aio/rpc_srv.py#L200

You can change that line to have it listen on all interfaces. VXI doesn't really support any security, so I defaulted it to only listen to localhost. Using SSH tunnels may be advised if you traverse a public network.

To create a new service, you should create a new "adapter" file, and create a reference to it from

https://github.com/pigrew/pyvxi11aio/blob/b1a02af8cc0c2e852bbe5c238d0ef612b4bd4c95/main.py#L52

I should also note that this project was for me to learn about asyncio and VXI, but I don't think it has been seriously used. It worked when I wrote it, but you'll probably need to dig into the code and perhaps fix things.

**Comment by ChevalierLouis** [comment]
Ok thanks I will try it 

Have a good day

**Comment by pigrew** [comment]
The main README file does have some hints, though I think I ended up implementing some of the things I said were not done in the "Current status".

Since your computer is Linux-based, you'll want to use the standard UNIX portmapper instead of the one in this repository (which was what I used on Windows). My expectation is that getting the portmapper running properly will be the biggest issue. To manually unmap things, you likely will have to be `root'.

If you fix bugs, or feel the need to write more documentation, don't hesitate to create a pull request with the changes.

**Comment by ChevalierLouis** [comment]
Ok no problems but I chose the easiest solution I use the coburnw one ,I
have found the issue : on the pi 4 and compute module 4 the wiring pi
module is different and you have to change it manually .
I think the "gpios"that I use are in conflict with the ethernet port so it
automatically disconnect of the network .



Le jeu. 20 mai 2021 à 21:09, Nathan Conrad ***@***.***> a
écrit :

**Comment by pigrew** [comment]
Alight.

I'll close this issue.
